package view;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import view.LauncherFrame.Message;

/**
 *
 * @author Martin Nilsson
 */
public class StartPanel extends javax.swing.JPanel {

	
	/**
	 * Creates new form StartPanel
	 */
	public StartPanel() {
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorLabel = new javax.swing.JLabel();
        hostButton = new javax.swing.JButton();
        joinButton = new javax.swing.JButton();
        ipTextField = new javax.swing.JTextField();
        optionsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        connectionErrorLabel = new javax.swing.JLabel();
        hostErrorLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        errorLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        errorLabel.setText("Could not connect.");

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(360, 480));
        setMinimumSize(new java.awt.Dimension(360, 480));
        setPreferredSize(new java.awt.Dimension(360, 480));

        hostButton.setMnemonic('H');
        hostButton.setText("Host");
        hostButton.setToolTipText("Host a game.");
        hostButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hostButton.setMaximumSize(new java.awt.Dimension(85, 23));
        hostButton.setMinimumSize(new java.awt.Dimension(85, 23));
        hostButton.setPreferredSize(new java.awt.Dimension(85, 23));
        hostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostButtonActionPerformed(evt);
            }
        });

        joinButton.setMnemonic('C');
        joinButton.setText("Connect");
        joinButton.setToolTipText("Join a game.");
        joinButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        joinButton.setMargin(new java.awt.Insets(2, 7, 2, 7));
        joinButton.setMaximumSize(new java.awt.Dimension(85, 23));
        joinButton.setMinimumSize(new java.awt.Dimension(85, 23));
        joinButton.setPreferredSize(new java.awt.Dimension(85, 23));
        joinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinButtonActionPerformed(evt);
            }
        });

        ipTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipTextField.setToolTipText("IP to host.");
        ipTextField.setMaximumSize(new java.awt.Dimension(100, 20));
        ipTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        ipTextField.setPreferredSize(new java.awt.Dimension(100, 20));

        optionsButton.setMnemonic('S');
        optionsButton.setText("Settings");
        optionsButton.setToolTipText("Change settings.");
        optionsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        optionsButton.setMaximumSize(new java.awt.Dimension(85, 23));
        optionsButton.setMinimumSize(new java.awt.Dimension(85, 23));
        optionsButton.setPreferredSize(new java.awt.Dimension(85, 23));
        optionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsButtonActionPerformed(evt);
            }
        });

        exitButton.setMnemonic('E');
        exitButton.setText("Exit");
        exitButton.setMaximumSize(new java.awt.Dimension(85, 23));
        exitButton.setMinimumSize(new java.awt.Dimension(85, 23));
        exitButton.setPreferredSize(new java.awt.Dimension(85, 23));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(120, 120, 120));
        jSeparator1.setForeground(new java.awt.Color(120, 120, 120));

        jSeparator2.setBackground(new java.awt.Color(120, 120, 120));
        jSeparator2.setForeground(new java.awt.Color(120, 120, 120));

        jSeparator3.setBackground(new java.awt.Color(120, 120, 120));
        jSeparator3.setForeground(new java.awt.Color(120, 120, 120));

        connectionErrorLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        connectionErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        connectionErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connectionErrorLabel.setText("Invalid IP, could not connect to host.");
        connectionErrorLabel.setAlignmentY(0.0F);
        connectionErrorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        hostErrorLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hostErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        hostErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostErrorLabel.setText("Port 5000 allready in use.");
        hostErrorLabel.setAlignmentY(0.0F);

        imageLabel.setBackground(new java.awt.Color(0, 0, 0));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LauncherImage.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addComponent(connectionErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hostErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(hostButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(joinButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(optionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(imageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hostButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(hostErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectionErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostButtonActionPerformed
		this.firePropertyChange(Message.HDIFTT_HOST.toString(), 0, 1);
    }//GEN-LAST:event_hostButtonActionPerformed

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinButtonActionPerformed
        this.firePropertyChange(Message.HDIFTT_JOIN.toString(), 0, 1);
    }//GEN-LAST:event_joinButtonActionPerformed

    private void optionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsButtonActionPerformed
        this.firePropertyChange(Message.HDIFTT_OPTIONS.toString(), 0, 1);
    }//GEN-LAST:event_optionsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.firePropertyChange(Message.HDIFTT_EXIT.toString(), 0, 1);
    }//GEN-LAST:event_exitButtonActionPerformed
	public String getIP(){
		return this.ipTextField.getText();
	}
	public void hideErrorMessages(){
		this.connectionErrorLabel.setVisible(false);
		this.hostErrorLabel.setVisible(false);
	}
	public void displayConnectionErrorMessage() {
		this.connectionErrorLabel.setVisible(true);
	}
	public void displayHostErrorMessage() {
		this.hostErrorLabel.setVisible(true);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connectionErrorLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hostButton;
    private javax.swing.JLabel hostErrorLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField ipTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton joinButton;
    private javax.swing.JButton optionsButton;
    // End of variables declaration//GEN-END:variables
}
